import Link from "next/link";
const sections = [
  { title: "1. Set up your workspace", body: "Sign in, create or join an organization, and choose it from the left sidebar. The organization keeps your team's boards together." },
  { title: "2. Create a board", body: "Choose Blank board or a starter template. On an empty board, describe a goal in Flowboard Assist or use a quick suggestion. AI chat and board generation require a configured provider. Generated content remains editable. You can stop a streaming response; if the provider is unavailable, use starter templates." },
  { title: "3. Use the canvas", body: "Select items to move or resize them. Sticky notes use a spacious FigJam-inspired layout with author, typeface, size, bold, strike, link, and list controls. The drawing palette provides pen, marker, styled strokes, eraser, widths, and colors. Shapes & Lines, Frames, and Stickers each open a focused insertion sidebar." },
  { title: "4. Edit and organize", body: "Click a board title to rename it. Use the star in the board header to add or remove it from Favourite boards. The board menu copies links or deletes boards. Select an item and press Delete or Backspace to remove it; Ctrl/Cmd+Z undoes a change." },
  { title: "5. Collaborate live", body: "Use Share on the board to copy its link for an organization teammate. When they open the same board, their cursors, selections, edits, and starter content appear live. A network connection and organization access are required." },
  { title: "6. Manage the organization", body: "Owners and admins can open Admin to view board creation, the ownership donut chart, contributors and recent boards. Use the visible Delete button to permanently remove a board after confirmation. In Members & Access, select a configured role and press Save role, or use Remove to revoke workspace membership. Manage access opens Clerk organization settings for invitations and advanced controls. Load remaining board pages before exporting a complete report. The world map is a geographic overview; member locations and visitor traffic are not collected." },
  { title: "7. Canvas 2D engine", body: "Open Canvas 2D from a board to use the optimized vector workspace. Select, Rectangle, Ellipse, Sticky and Pencil tools appear on the left. Hold Space and drag to pan, or choose the Pan tool on touch devices. Scroll to zoom around the pointer. Select an item to change its fill or stroke. Use arrow keys to move, Page Up or Page Down to change stacking order, Enter to edit text, and Delete or Backspace to remove it. New persistent edits pause when the network is offline." },
  { title: "8. Roles and access", body: "Owner and Admin can administer the workspace. Member can create and edit boards. Guest has read access. Unknown roles fail closed. Clerk supplies Admin and Member by default; custom Owner or Guest roles must be configured by your instance administrator. Removing a workspace member does not delete their Clerk account. Role changes may require the member to refresh their session." },
  { title: "9. Install the app", body: "On a supported mobile or desktop browser, use Install app or Add to Home Screen from the browser menu. Boards still need an internet connection." },
  { title: "10. Personalize Flowboard", body: "Open Settings to choose Light, Dark, or System appearance. Canvas preferences control the grid, contrast, and motion. The plus button opens a searchable Tools and Marketplace catalog. In Diagram & Shapes, click a +N shapes control to reveal exactly N insertable shapes from that pack." },
];
export default function GuidePage() {
  return <div className="px-3 sm:px-6 pb-10 max-w-[1050px]">
    <p className="text-xs uppercase tracking-[.2em] font-bold text-orange-700 dark:text-orange-400">Help center</p><h1 className="text-3xl font-bold mt-1">Flowboard guide</h1><p className="text-sm text-muted-foreground mt-2 mb-7">Everything you need to get started and work with your team.</p>
    <div className="grid md:grid-cols-2 gap-4">{sections.map(section => <section key={section.title} className="rounded-xl border border-border bg-card p-6 shadow-sm"><h2 className="font-semibold">{section.title}</h2><p className="text-sm text-muted-foreground mt-3 leading-6">{section.body}</p></section>)}</div>
    <div className="mt-6 flex gap-3"><Link href="/templates" className="rounded-md bg-[#4262ff] px-4 py-2 text-white font-semibold text-sm">Explore templates</Link><Link href="/" className="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold">Go to boards</Link></div>
  </div>;
}
