"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, BookOpen, Search, Rocket, MousePointer2, Users, ShieldCheck, Download, Palette, Layers3, Sparkles, Settings, Keyboard, Gamepad2 } from "lucide-react";
import "./guide.css";
const sections = [
  { title: "1. Set up your workspace", body: "Sign in, create or join an organization, and choose it from the left sidebar. The organization keeps your team's boards together." },
  { title: "2. Create a board", body: "Choose Blank board or a starter template. On an empty board, describe a goal in Flowboard Assist or use a quick suggestion. AI chat and board generation require a configured provider. Generated content remains editable. You can stop a streaming response; if the provider is unavailable, use starter templates." },
  { title: "3. Use the canvas", body: "Select items to move or resize them. Sticky notes use a spacious FigJam-inspired layout with author, typeface, size, bold, strike, link, and list controls. The drawing palette provides pen, marker, styled strokes, eraser, widths, and colors. Shapes & Lines, Frames, and Stickers each open a focused insertion sidebar." },
  { title: "4. Edit and organize", body: "Click a board title to rename it. Use the star in the board header to add or remove it from Favourite boards. The board menu copies links or deletes boards. Select an item and press Delete or Backspace to remove it; Ctrl/Cmd+Z undoes a change." },
  { title: "5. Collaborate live", body: "Use Share on the board to copy its link for an organization teammate. When they open the same board, their cursors, selections, edits, and starter content appear live. A network connection and organization access are required." },
  { title: "6. Manage the organization", body: "Owners and admins can open Admin to view board creation, the ownership donut chart, contributors and recent boards. Use the visible Delete button to permanently remove a board after confirmation. In Members & Access, select a configured role and press Save role, or use Remove to revoke workspace membership. Manage access opens Clerk organization settings for invitations and advanced controls. Load remaining board pages before exporting a complete report. The world map is a geographic overview; member locations and visitor traffic are not collected." },
  { title: "7. Canvas 2D engine", body: "Open Canvas 2D from a board to use the optimized vector workspace. Select, Rectangle, Ellipse, Sticky and Pencil tools appear on the left. Hold Space and drag to pan, or choose the Pan tool on touch devices. Scroll to zoom around the pointer. Select an item to change its fill or stroke. Use arrow keys to move, Page Up or Page Down to change stacking order, Enter to edit text, and Delete or Backspace to remove it. New persistent edits pause when the network is offline." },
  { title: "8. Roles and access", body: "Owner and Admin can administer the workspace. Member can create and edit boards. Guest has read access. Unknown roles fail closed. Clerk supplies Admin and Member by default; custom Owner or Guest roles must be configured by your instance administrator. Removing a workspace member does not delete their Clerk account. Role changes may require the member to refresh their session." },
  { title: "9. Install the app", body: "On a supported mobile or desktop browser, use Install app or Add to Home Screen from the browser menu. Boards still need an internet connection." },
  { title: "10. Personalize Flowboard", body: "Open Settings to choose Light, Dark, or System appearance. Canvas preferences control the grid, contrast, and motion. The plus button opens a searchable Tools and Marketplace catalog. In Diagram & Shapes, click a +N shapes control to reveal exactly N insertable shapes from that pack." },
];

const icons = [Users, Rocket, MousePointer2, Layers3, Users, ShieldCheck, Layers3, ShieldCheck, Download, Palette];
export default function GuidePage() {
  const [query, setQuery] = useState("");
  const filtered = sections.map((section,index) => ({...section,index})).filter(section => `${section.title} ${section.body}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="docs-center">
    <header className="docs-hero"><div><p className="docs-eyebrow"><BookOpen size={16} aria-hidden="true" /> FLOWBOARD DOCUMENTATION</p><h1>Find your flow.</h1><p>From your first idea to a shared workspace. Practical guides for every step.</p></div><label className="docs-search"><Search size={20} aria-hidden="true" /><input value={query} onChange={event => setQuery(event.target.value)} aria-label="Search documentation" placeholder="Search tools, roles, shortcuts…" />{query && <button onClick={() => setQuery("")} aria-label="Clear documentation search">Clear</button>}</label></header>
    <div className="docs-quick-links">{[{href:"/templates",icon:Sparkles,title:"Start with a template",copy:"Skip the blank canvas."},{href:"/settings",icon:Settings,title:"Make it yours",copy:"Appearance and preferences."},{href:"/games",icon:Gamepad2,title:"Take a creative break",copy:"Explore the arcade."}].map(({href,icon:Icon,title,copy})=><Link key={href} href={href}><Icon size={22} aria-hidden="true" /><div><strong>{title}</strong><p>{copy}</p></div><ArrowUpRight size={17} aria-hidden="true" /></Link>)}</div>
    <div className="docs-layout"><aside><p className="docs-eyebrow">IN THIS GUIDE</p><nav aria-label="Documentation topics">{filtered.map(section=><a key={section.index} href={`#topic-${section.index}`}>{section.title.replace(/^\d+\. /,"")}</a>)}</nav><div className="docs-tip"><Keyboard size={20} aria-hidden="true" /><strong>Work at your own pace</strong><p>Use Settings to reduce motion or increase canvas contrast.</p></div></aside><div className="docs-articles"><p className="docs-results" role="status">{filtered.length} {filtered.length === 1 ? "topic" : "topics"}{query ? ` matching “${query}”` : " to explore"}</p>{filtered.map(section=>{const Icon=icons[section.index];return <article id={`topic-${section.index}`} key={section.index}><details open={query ? true : undefined}><summary><span className="docs-topic-icon"><Icon size={21} aria-hidden="true" /></span><h2>{section.title.replace(/^\d+\. /,"")}</h2><span className="docs-expand" aria-hidden="true">+</span></summary><p>{section.body}</p></details></article>})}{!filtered.length && <div className="docs-empty"><Search size={30} aria-hidden="true" /><h2>No matching topics</h2><p>Try “canvas”, “roles”, or “share”.</p><button onClick={()=>setQuery("")}>Show all topics</button></div>}<section className="docs-shortcuts"><h2><Keyboard size={20} aria-hidden="true" /> Everyday shortcuts</h2><dl>{[["Undo","Ctrl / ⌘ + Z"],["Pan canvas","Space + drag"],["Delete selection","Delete / Backspace"],["Find a destination","Ctrl / ⌘ + K"]].map(([label,key])=><div key={label}><dt>{label}</dt><dd><kbd>{key}</kbd></dd></div>)}</dl></section></div></div>
  </div>;
}
