"use client";
import { useState } from "react";
import Link from "next/link";
import { BarChart3, CheckCircle2, FileText, MessageSquare, Plus, Target, Trash2 } from "lucide-react";
import { useMutation, useSelf, useStorage } from "@liveblocks/react/suspense";
import { LiveObject } from "@liveblocks/client";
import { nanoid } from "nanoid";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Layer, LayerType, NoteLayer } from "@/types/canvas";
import { MAX_LAYERS } from "@/lib/board-portability";
import { toast } from "sonner";

const sections = [{ key: "problem", title: "Problem & context", hint: "Who is this for? What problem are we solving?", color: "bg-indigo-600" }, { key: "goals", title: "Goals & outcomes", hint: "Define the desired outcomes and what is out of scope.", color: "bg-pink-600" }, { key: "metrics", title: "Success metrics", hint: "How will you measure success? Include targets and a timeframe.", color: "bg-green-600" }, { key: "risks", title: "Risks & dependencies", hint: "Document assumptions, blockers, and dependencies.", color: "bg-amber-600" }] as const;
const text = (value = "") => value.replace(/<[^>]*>/g, "").replaceAll("&lt;", "<").replaceAll("&gt;", ">").replaceAll("&amp;", "&");
const encode = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

export function RequirementsWorkspace({ onCanvas }: { onCanvas: () => void }) {
  const [tab, setTab] = useState("Overview");
  const [draft, setDraft] = useState("");
  const [search, setSearch] = useState("");
  const name = useSelf(me => me.info?.name || "Team member");
  const notes = useStorage(root => root.layerIds.flatMap(id => { const layer = root.layers[id]; return layer?.type === LayerType.Note && layer.requirementSection ? [{ id, ...layer }] : []; }));
  const title = useStorage(root => root.layerIds.map(id => root.layers[id]).find(layer => layer?.type === LayerType.Text)?.value || "Product requirements");
  const requirements = notes.filter(note => note.requirementSection === "requirements");
  const completed = requirements.filter(note => note.status === "done").length;
  const add = useMutation(({ storage }, section: NonNullable<NoteLayer["requirementSection"]>, value: string, id?: string) => {
    const layers = storage.get("layers");
    if (id && layers.has(id)) { layers.get(id)?.set("value", encode(value)); return; }
    if (layers.size >= MAX_LAYERS) { toast.error("Board object limit reached."); return; }
    const key = id || nanoid();
    layers.set(key, new LiveObject<Layer>({ type: LayerType.Note, x: 190 + notes.length % 4 * 300, y: 240 + Math.floor(notes.length / 4) * 240, width: 280, height: 210, fill: { r: 181, g: 216, b: 255, a: 1 }, value: encode(value), author: name, requirementSection: section, requirementPriority: "must", status: "planned" }));
    storage.get("layerIds").push(key);
  }, [notes.length, name]);
  const update = useMutation(({ storage }, id: string, patch: Partial<NoteLayer>) => { storage.get("layers").get(id)?.update(patch); }, []);
  const remove = useMutation(({ storage }, id: string) => { storage.get("layers").delete(id); const ids = storage.get("layerIds"); const index = ids.indexOf(id); if (index >= 0) ids.delete(index); }, []);
  return <main className="h-dvh bg-gradient-to-br from-slate-100 via-indigo-50 to-blue-100 p-3 text-foreground dark:from-slate-950 dark:via-slate-950 dark:to-indigo-950 md:p-7"><div className="mx-auto flex h-full max-w-7xl overflow-hidden rounded-2xl border bg-background shadow-xl">
    <aside className="hidden w-60 shrink-0 flex-col border-r bg-muted/20 p-4 lg:flex"><Link href="/" className="mb-7 flex items-center gap-2 font-semibold"><FileText size={20} className="text-indigo-600 dark:text-indigo-300" />Flowboard</Link><div className="mb-5 rounded-xl border bg-background p-4"><span className="mb-3 inline-flex rounded bg-indigo-100 p-2 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-200"><FileText size={20} /></span><p className="text-sm font-semibold">Product Requirements</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Define the problem, align your team, and track delivery.</p></div>{["Overview", "Planning", "Progress", "Discussion"].map(label => <Button key={label} variant={tab === label ? "secondary" : "ghost"} className="mb-2 justify-start" onClick={() => setTab(label)}>{label}</Button>)}<Link href="/guide" className="mt-auto text-xs text-muted-foreground">Help Center</Link></aside>
    <section className="flex min-w-0 flex-1 flex-col"><header className="flex items-center gap-3 border-b p-4"><span className="mr-auto truncate text-sm font-semibold">{text(title)}</span><Button variant="outline" size="sm" onClick={onCanvas}>Canvas</Button></header><nav className="flex gap-2 overflow-auto border-b px-5 py-3">{["Overview", "Planning", "Progress", "Discussion"].map(label => <button key={label} aria-pressed={tab === label} onClick={() => setTab(label)} className={`rounded-full border px-3 py-1 text-xs ${tab === label ? "bg-muted font-semibold" : "text-muted-foreground hover:bg-muted"}`}>{label}</button>)}</nav>
      <div className="flex-1 overflow-auto p-5 md:p-8"><div className="mx-auto max-w-3xl"><h1 className="mb-2 text-2xl font-semibold">{text(title)}</h1><p className="mb-7 text-sm text-muted-foreground">A shared source of truth for your next product release.</p>
        {tab === "Overview" && sections.map(section => { const saved = notes.find(note => note.requirementSection === section.key); return <section key={section.key} className="mb-6 border-t pt-5"><h2 className="mb-3 flex items-center gap-2 text-base font-semibold"><span className={`rounded p-1 text-white ${section.color}`}><FileText size={13} /></span>{section.title}</h2><textarea aria-label={section.title} defaultValue={text(saved?.value)} key={saved?.value || section.key} placeholder={section.hint} maxLength={4000} onBlur={event => { if (event.target.value !== text(saved?.value)) add(section.key, event.target.value, saved?.id || `prd-section-${section.key}`); }} className="min-h-28 w-full resize-y rounded-xl border bg-background p-3 text-sm leading-6 outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-indigo-500" /><p className="mt-1 text-xs text-muted-foreground">Saves when you leave this field.</p></section>; })}
        {tab === "Planning" && <><h2 className="mb-4 flex items-center gap-2 font-semibold"><Target size={18} />Requirements & acceptance criteria</h2><Input aria-label="Search requirements" placeholder="Search requirements" value={search} onChange={event => setSearch(event.target.value)} className="mb-4" /><form className="mb-6 flex gap-2" onSubmit={event => { event.preventDefault(); if (!draft.trim()) return; add("requirements", draft.trim()); setDraft(""); }}><Input aria-label="New requirement" placeholder="Add a requirement" maxLength={1000} value={draft} onChange={event => setDraft(event.target.value)} required /><Button type="submit"><Plus size={16} />Add</Button></form>{requirements.filter(note => text(note.value).toLowerCase().includes(search.toLowerCase())).map(note => <article key={note.id} className="mb-4 rounded-xl border p-4 shadow-sm"><div className="mb-3 flex gap-2"><input aria-label="Requirement title" defaultValue={text(note.value)} key={note.value} maxLength={1000} onBlur={event => { if (event.target.value.trim()) update(note.id, { value: encode(event.target.value.trim()) }); }} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none focus:ring-2 focus:ring-ring" /><button aria-label="Delete requirement" onClick={() => remove(note.id)}><Trash2 size={14} /></button></div><textarea aria-label="Acceptance criteria" defaultValue={note.description || ""} key={note.description} placeholder="Acceptance criteria: what must be true for this to be complete?" maxLength={2000} onBlur={event => update(note.id, { description: event.target.value })} className="mb-3 min-h-20 w-full rounded border bg-muted/20 p-2 text-sm outline-none focus:ring-2 focus:ring-ring" /><div className="flex flex-wrap gap-3"><select aria-label="Requirement priority" className="rounded border bg-background p-1 text-xs" value={note.requirementPriority || "must"} onChange={event => update(note.id, { requirementPriority: event.target.value as NoteLayer["requirementPriority"] })}><option value="must">Must have</option><option value="should">Should have</option><option value="could">Could have</option></select><select aria-label="Requirement status" className="rounded border bg-background p-1 text-xs" value={note.status || "planned"} onChange={event => update(note.id, { status: event.target.value as NoteLayer["status"] })}><option value="planned">Planned</option><option value="in-progress">In progress</option><option value="done">Done</option></select><span className="ml-auto text-xs text-muted-foreground">{note.author}</span></div></article>)}</>}
        {tab === "Progress" && <><h2 className="mb-5 flex items-center gap-2 font-semibold"><BarChart3 size={18} />Delivery progress</h2><div className="mb-7 grid gap-3 sm:grid-cols-3">{[{ label: "Requirements", value: requirements.length }, { label: "Completed", value: completed }, { label: "Completion", value: `${requirements.length ? Math.round(completed / requirements.length * 100) : 0}%` }].map(metric => <div key={metric.label} className="rounded-xl border p-4"><p className="mb-2 text-xs text-muted-foreground">{metric.label}</p><strong className="text-2xl">{metric.value}</strong></div>)}</div><div className="space-y-5 rounded-xl border p-5">{["planned", "in-progress", "done"].map(status => { const count = requirements.filter(note => (note.status || "planned") === status).length; return <div key={status}><div className="mb-2 flex justify-between text-sm"><span>{status === "in-progress" ? "In progress" : status === "done" ? "Done" : "Planned"}</span><span>{count}</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className={`h-full ${status === "done" ? "bg-green-600" : status === "in-progress" ? "bg-indigo-500" : "bg-slate-400"}`} style={{ width: `${requirements.length ? count / requirements.length * 100 : 0}%` }} /></div></div>; })}</div></>}
        {tab === "Discussion" && <><h2 className="mb-5 flex items-center gap-2 font-semibold"><MessageSquare size={18} />Team discussion</h2>{notes.filter(note => note.requirementSection === "discussion").map(note => <article key={note.id} className="mb-3 rounded-xl border p-4"><div className="mb-2 flex justify-between text-xs font-semibold"><span>{note.author}</span><button aria-label="Delete discussion note" onClick={() => remove(note.id)}><Trash2 size={14} /></button></div><p className="whitespace-pre-wrap text-sm leading-6">{text(note.value)}</p></article>)}<form onSubmit={event => { event.preventDefault(); if (!draft.trim()) return; add("discussion", draft.trim()); setDraft(""); }}><textarea aria-label="Discussion note" placeholder="Share a question or decision with the team" maxLength={1000} value={draft} onChange={event => setDraft(event.target.value)} className="min-h-28 w-full rounded-xl border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /><Button type="submit" className="mt-3" disabled={!draft.trim()}>Post note</Button></form></>}
      </div></div>
    </section><aside className="hidden w-56 shrink-0 border-l bg-muted/10 p-5 xl:block"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-indigo-400 bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-100"><FileText size={26} /></span><h2 className="mt-4 font-semibold">Product brief</h2><p className="mt-2 text-xs text-muted-foreground">Shared workspace</p><div className="my-5 rounded-xl border bg-background p-4"><p className="mb-3 text-xs text-muted-foreground">Readiness</p><strong className="text-2xl">{sections.filter(section => notes.some(note => note.requirementSection === section.key && text(note.value).trim())).length}/4</strong><p className="mt-2 text-xs text-muted-foreground">Overview sections filled</p></div><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide">Key observations</h3><p className="mb-4 flex gap-2 text-xs leading-5"><CheckCircle2 size={16} className="shrink-0 text-green-600 dark:text-green-300" />{completed} of {requirements.length} requirements complete</p><p className="text-xs leading-5 text-muted-foreground">Define acceptance criteria and priorities in Planning to keep delivery focused.</p></aside>
  </div></main>;
}
